In [2]:
# Question 1
import numpy as np91

In [3]:
array = np91.array([[4,6,9],[5,7,3],[9,1,7]])

In [4]:
array

array([[4, 6, 9],
       [5, 7, 3],
       [9, 1, 7]])

In [5]:
arr = np91.zeros((3,4))

In [6]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
array[1][2]

3

In [8]:
max = np91.max(array, axis=0)

In [9]:
max

array([9, 7, 9])

In [10]:
mean_value = np91.mean(array, axis=1)

In [11]:
mean_value

array([6.33333333, 5.        , 5.66666667])

In [12]:
array[1:3, 1:3]

array([[7, 3],
       [1, 7]])

In [13]:
#Question 3
import pandas as pd91

In [14]:
data = {
    "Name":[],
    "Age":[],
    "Roll Number":[]
}

In [15]:
pd91.DataFrame(data)

Empty DataFrame
Columns: [Name, Age, Roll Number]
Index: []

In [16]:
#Question 2 
A = np91.array([5,3,6,9,3,6,9,1,4,1])

In [17]:
np91.mean(A)

4.7

In [18]:
np91.median(A)

4.5

In [19]:
import statistics as stat
stat.mode(A)

3

In [21]:
#For Interquartile Range
Median1 = np91.percentile(A, 25)
Median2 = np91.percentile(A, 75)


In [22]:
IQR = Median2 - Median1

In [23]:
IQR

3.0