Examples

In [3]:
import numpy as np

# Creating an array
a = np.array([1, 2, 3])

# Adding two arrays
b = np.array([4, 5, 6])

# Multiplying an array by a number
c = a * 2


# Finding the mean of an array
d = np.mean(a)

# Finding the standard deviation of an array
e = np.std(a)

# Finding the maximum value in an array
f = np.max(a)

# Finding the minimum value in an array
g = np.min(a)

# Finding the sum of all the values in an array
h = np.sum(a)

# Finding the number of elements in an array
i = np.size(a)

# Sorting an array
j = np.sort(a)

# Reversing the order of an array
k = np.flip(a)

# Joining two arrays
m = np.concatenate((a, b))

print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)
print(k)
print(m)

[2 4 6]
2.0
0.816496580927726
3
1
6
3
[1 2 3]
[3 2 1]
[1 2 3 4 5 6]
